/*

 HUB_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : hub.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hub_mapWidth 20
#define hub_mapHeight 1
#define hub_mapBank 0

const unsigned char hub_map[] =
{
  0x67,0x67,0x67,0x66,0x66,0x68,0x69,0x6A,0x6B,0x6C,
  0x6D,0x5C,0x5C,0x5C,0x5C,0x5C,0x66,0x66,0x66,0x66
};

/* End of HUB_MAP.C */
