/*

 HUB_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : hub.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hub_mapWidth 20
#define hub_mapHeight 1
#define hub_mapBank 0

extern unsigned char hub_map[];

/* End of HUB_MAP.H */
